### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by andrewcalimlim** [Elegant-Queueing/employee-version#1]
I got through the first three steps of User Guide> "Installation, Run & Use the Web App (beta)" , however after entering in "codealot@code.com" and no password, pressing the "Login" button does nothing and I get stuck on the home page

**Comment by Alex-Zhang10** [comment]
We implemented firebase authentication in the q-backend but at the time of peer reviewing the corresponding front-end code wasn't pushed. Now all working
